version: '3.8'

services:
  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    ports:
      - "8089:8080"
    environment:
      - NC_DB=pg://nocodb-postgres:5432?u=nocodb&p=nocodb123&d=nocodb
      - NC_AUTH_JWT_SECRET=nocodb-jwt-secret
      - NC_REDIS_URL=redis://nocodb-redis:6379
    depends_on:
      - nocodb-postgres
      - nocodb-redis
    volumes:
      - nocodb_data:/usr/app/data
    networks:
      - nocodb_network
    restart: unless-stopped

  nocodb-postgres:
    image: postgres:13
    container_name: nocodb-postgres
    environment:
      - POSTGRES_DB=nocodb
      - POSTGRES_USER=nocodb
      - POSTGRES_PASSWORD=nocodb123
    volumes:
      - nocodb_postgres_data:/var/lib/postgresql/data
    networks:
      - nocodb_network
    restart: unless-stopped

  nocodb-redis:
    image: redis:7-alpine
    container_name: nocodb-redis
    volumes:
      - nocodb_redis_data:/data
    networks:
      - nocodb_network
    restart: unless-stopped

volumes:
  nocodb_data:
  nocodb_postgres_data:
  nocodb_redis_data:

networks:
  nocodb_network:
    driver: bridge