version: '3.8'

services:
  langfuse:
    image: langfuse/langfuse:latest
    container_name: langfuse
    ports:
      - "3004:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/langfuse
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - NEXTAUTH_URL=http://localhost:3004
    depends_on:
      - postgres
    volumes:
      - langfuse_data:/app/.next
    networks:
      - langfuse_network

  postgres:
    image: postgres:15
    container_name: langfuse_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=langfuse
    volumes:
      - langfuse_postgres_data:/var/lib/postgresql/data
    networks:
      - langfuse_network

volumes:
  langfuse_data:
  langfuse_postgres_data:

networks:
  langfuse_network:
    driver: bridge