version: '3.8'

services:
  langflow:
    image: langflowai/langflow:latest
    container_name: langflow
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_DATABASE_URL=sqlite:///./langflow.db
      - LANGFLOW_AUTO_LOGIN=false
    volumes:
      - langflow_data:/app/langflow
    networks:
      - langflow_network
    restart: unless-stopped

volumes:
  langflow_data:

networks:
  langflow_network:
    driver: bridge