version: '3.8'

services:
  ghost:
    image: ghost:latest
    container_name: ghost
    ports:
      - "8094:2368"
    environment:
      - url=http://localhost:8094
      - database__client=mysql
      - database__connection__host=ghost-mysql
      - database__connection__user=ghost
      - database__connection__password=ghost123
      - database__connection__database=ghost
      - mail__transport=SMTP
      - mail__options__service=Mailgun
      - mail__options__auth__user=postmaster@mg.example.com
      - mail__options__auth__pass=password
    depends_on:
      - ghost-mysql
    volumes:
      - ghost_data:/var/lib/ghost/content
    networks:
      - ghost_network
    restart: unless-stopped

  ghost-mysql:
    image: mysql:8.0
    container_name: ghost-mysql
    environment:
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=ghost123
      - MYSQL_ROOT_PASSWORD=root123
    volumes:
      - ghost_mysql_data:/var/lib/mysql
    networks:
      - ghost_network
    restart: unless-stopped

volumes:
  ghost_data:
  ghost_mysql_data:

networks:
  ghost_network:
    driver: bridge