version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    ports:
      - "3012:3001"
    volumes:
      - uptime_kuma_data:/app/data
    networks:
      - uptime_kuma_network
    restart: unless-stopped

volumes:
  uptime_kuma_data:

networks:
  uptime_kuma_network:
    driver: bridge