version: '3.8'

services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    ports:
      - "3017:80"
    networks:
      - excalidraw_network
    restart: unless-stopped

networks:
  excalidraw_network:
    driver: bridge