version: '3.8'

services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    ports:
      - "8102:8080"
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_US
    volumes:
      - stirling_data:/usr/share/tessdata
      - stirling_configs:/configs
    networks:
      - stirling_network
    restart: unless-stopped

volumes:
  stirling_data:
  stirling_configs:

networks:
  stirling_network:
    driver: bridge