version: '3.8'

services:
  mattermost:
    image: mattermost/mattermost-team-edition:latest
    container_name: mattermost
    ports:
      - "8065:8065"
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@postgres:5432/mattermost?sslmode=disable
      - MM_SERVICESETTINGS_SITEURL=http://localhost:8065
    depends_on:
      - postgres
    volumes:
      - mattermost_data:/mattermost/data
      - mattermost_logs:/mattermost/logs
      - mattermost_config:/mattermost/config
    networks:
      - mattermost_network

  postgres:
    image: postgres:15
    container_name: mattermost_postgres
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    volumes:
      - mattermost_postgres_data:/var/lib/postgresql/data
    networks:
      - mattermost_network

volumes:
  mattermost_data:
  mattermost_logs:
  mattermost_config:
  mattermost_postgres_data:

networks:
  mattermost_network:
    driver: bridge